// @flow
export const ADD_MAIN_CHART_SET_SHOW = 'ADD_MAIN_CHART_SET_SHOW';
export const ADD_MAIN_CHART_SET_SELECTED_EXCHANGE = 'ADD_MAIN_CHART_SET_SELECTED_EXCHANGE';
export const ADD_MAIN_CHART_SET_SELECTED_SYMBOL = 'ADD_MAIN_CHART_SET_SELECTED_SYMBOL';
