//@flow
export const HYDRATE_PROFILE_DATA = "HYDRATE_PROFILE_DATA";
export const LOADED_PROFILE_DATA = "LOADED_PROFILE_DATA";
export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const CHANGE_PROFILE_NAME = "CHANGE_PROFILE_NAME";
