//
// import { PROFILE_CREATOR_STAGES } from '../actions/ui';

const PROFILE_CREATOR_STAGES = {
  ACCOUNT_ADDER: "ACCOUNT_ADDER",
  ADD_BALANCE: "ADD_BALANCE",
  ADD_EXCHANGE: "ADD_EXCHANGE",
  ADD_WALLET: "ADD_WALLET"
};
