//
export const SET_MAIN_PANEL_EDIT_MODE = "SET_MAIN_PANEL_EDIT_MODE";
export const UPDATE_MAIN_LAYOUTS = "UPDATE_MAIN_LAYOUTS";
export const LOADED_UI_DATA = "LOADED_UI_DATA";
export const SET_SHOW_ADD_MAIN_CHART = "SET_SHOW_ADD_MAIN_CHART";
export const SET_OFFERED_CREATOR = "SET_OFFERED_CREATOR";
export const SET_PROFILE_CREATOR_STAGE = "SET_PROFILE_CREATOR_STAGE";
export const SET_SHOW_PROFILE_CREATOR = "SET_SHOW_PROFILE_CREATOR";

/**
 * Profile Creator Stage type
 * @todo description
 */
export const PROFILE_CREATOR_STAGES = {
  ACCOUNT_ADDER: "ACCOUNT_ADDER",
  ADD_BALANCE: "ADD_BALANCE",
  ADD_EXCHANGE: "ADD_EXCHANGE",
  ADD_WALLET: "ADD_WALLET"
};
